src/docker/buildfiles/opt/ada/app/src/Entity/RemoteAnalysis.php
<?php
declare(strict_types = 1);

namespace App\Entity;

use App\Enum\AnalysisStatus;
use App\Enum\AnalysisType;
use App\Enum\FileFormat;
use DateTimeImmutable;
use Symfony\Component\Intl\Countries;

class RemoteAnalysis
{
    /**
     * @param iterable<RemoteUpload> $uploaded
     */
    private function __construct(
        protected readonly int $id,
        protected readonly AnalysisType $type,
        protected readonly ?bool $subSpeciesLevel,
        protected readonly ?bool $sensitveMode,
        protected readonly AnalysisStatus $status,
        protected readonly \DateTimeInterface $created,
        protected readonly ?\DateTimeInterface $lastReport,
        protected readonly \DateTimeInterface $runUntil,
        protected readonly ?\DateTimeImmutable $finishedTime,
        protected readonly ?string $finishedReason,
        protected readonly iterable $uploaded,
        protected readonly FileFormat $format,
        protected readonly ?string $flowcellType,
        protected readonly ?string $libraryToolkit,
        protected readonly string $name,
        protected readonly ?float $latitude,
        protected readonly ?float $longitude,
        protected readonly string $country,
        protected readonly ?string $city,
        protected readonly ?string $host,
        protected readonly int $minQualityScore,
        protected readonly int $minSequenceLength,
    ) {}

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return \App\Enum\AnalysisType
     */
    public function getType(): ?AnalysisType
    {
        return $this->type;
    }

    /**
     * @return bool|null
     */
    public function getSubSpeciesLevel(): ?bool
    {
        return $this->subSpeciesLevel;
    }

    /**
     * @return bool|null
     */
    public function getSensitiveMode(): ?bool
    {
        return $this->sensitveMode;
    }

    /**
     * @return \App\Enum\AnalysisStatus
     */
    public function getStatus(): ?AnalysisStatus
    {
        return $this->status;
    }

    /**
     * @return \DateTimeInterface
     */
    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getLastReport(): ?\DateTimeInterface
    {
        return $this->lastReport;
    }

    /**
     * @return \DateTimeInterface
     */
    public function getRunUntil(): ?\DateTimeInterface
    {
        return $this->runUntil;
    }

    /**
     * @return \DateTimeImmutable|null
     */
    public function getFinishedTime(): ?\DateTimeImmutable
    {
        return $this->finishedTime;
    }

    /**
     * @return string|null
     */
    public function getFinishedReason(): ?string
    {
        return $this->finishedReason;
    }

    /**
     * @return iterable<\App\Entity\RemoteUpload>|null
     */
    public function getUploaded(): ?iterable
    {
        return $this->uploaded;
    }

    public function getFormat(): ?FileFormat
    {
        return $this->format;
    }

    public function getFlowcellType(): ?string
    {
        return $this->flowcellType;
    }

    /**
     * @return string|null
     */
    public function getLibraryToolkit(): ?string
    {
        return $this->libraryToolkit;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function getCountryName(): ?string
    {
        return $this->country ?
            Countries::getName($this->country) :
            null;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function getHost(): ?string
    {
        return $this->host;
    }

    public function getMinQualityScore(): ?int
    {
        return $this->minQualityScore;
    }

    public function getMinSequenceLength(): ?int
    {
        return $this->minSequenceLength;
    }

    public static function fromResponse(\stdClass $json) {
        return new self(
            $json->id,
            AnalysisType::from($json->type->type),
            $json->type->subSpeciedLevel ?? null,
            $json->type->sensitiveMode ?? null,
            AnalysisStatus::tryFrom($json->status) ??
                AnalysisStatus::unknown,
            new \DateTimeImmutable($json->created),
            isset($json->lastReport) ?
                new \DateTimeImmutable($json->lastReport) :
                null,
            new \DateTimeImmutable($json->runUntil),
            (($json->finished ?? null)?->time ?? null) ?
                new \DateTimeImmutable($json->finished->time) :
                null,
            ($json->finished ?? null)?->reason ?? null,
            array_map(
                fn(\stdClass $upload) => new RemoteUpload(
                    $upload->fileName,
                    $upload->size ?? null,
                    $upload->crc32 ?? null,
                ),
                $json->uploaded,
            ),
            FileFormat::from($json->format->type),
            $json->format->flowcellType ?? null,
            $json->format->libraryToolkit ?? null,
            $json->name,
            $json->location->latitude ?? null,
            $json->location->longitude ?? null,
            $json->location->country,
            $json->location->city ?? null,
            $json->host ?? null,
            $json->minQualityScore,
            $json->minSequenceLength,
        );
    }

    final public function portalPath(string $locale) {
        $parameters = [
            'action' => 'detail',
            'controller' => 'PipelineAnalysis',
            'pipeline' => $this->getId()
        ];

        // Wrap the parameters with tx_rapidpipeline_pipelineanalysis[…]
        $parameters = array_combine(
            array_map(
                fn(string $name) => "tx_rapidpipeline_pipelineanalysis[$name]",
                array_keys($parameters)
            ),
            array_values($parameters)
        );

        $parameterString = http_build_query($parameters);

        return match ($locale) {
            'de' => 'analysen/details',
            'en' => 'analyses/details',
        } . '?' . $parameterString;
    }

    public function getRunningTime(): array
    {
        $runningTimeEnd = $this->getStatus()->isFinished() ? $this->getFinishedTime() : new DateTimeImmutable();
        $diff = $runningTimeEnd->diff($this->getCreated(), true);

        return [
            'hours' => $diff->days * 24 + $diff->h,
            'minutes' => $diff->i,
        ];
    }
}

src/docker/buildfiles/opt/ada/app/src/Controller/AnalysisController.php
<?php
declare(strict_types = 1);

namespace App\Controller;

use App\Entity\Analysis;
use App\Entity\RemoteAnalysis;
use App\Entity\Token;
use App\Enum\AnalysisStatus;
use App\Enum\CreateAnalysisError;
use App\Enum\GetAnalysisError;
use App\Enum\UpdateStatusError;
use App\Form\AnalysisForm;
use App\Form\Entity\UpdateStatus;
use App\Form\UpdateStatusType;
use App\Repository\AnalysisRepository;
use App\Repository\UploadRepository;
use App\Service\ApiService;
use App\Service\CurrentAnalysisFactory;
use App\Service\PortalUrl;
use Doctrine\Common\Collections\Criteria;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;
use Twig\Error\RuntimeError;

final class AnalysisController extends AbstractController
{
    public function __construct(
        private readonly ApiService $api,
        private readonly AnalysisRepository $analyses,
        private readonly UploadRepository $uploads,
        private readonly FormFactoryInterface $forms,
    ) {}

    #[Route(
        path: '/{_locale}/analysis',
        name: 'app_page_analysis_show',
        requirements: [
            '_locale' => 'en|de',
        ],
    )]
    public function analysis(
        Request $request,
        CurrentAnalysisFactory $analysisFactory,
        TranslatorInterface $i18n,
        PortalUrl $portal,
        string $_locale,
    ): Response
    {
        if (!$analysisFactory->isRegistered()) {
            return $this->redirectToRoute('app_page_analysis_register');
        }

        $analysis = $analysisFactory->forceFetch();

        if ($analysis instanceof GetAnalysisError) {
            if ($analysis === GetAnalysisError::InvalidToken) {
                return $this->forward(
                    ErrorController::class . '::invalidToken',
                    [
                        '_locale' => $_locale,
                        ...$request->attributes->all(),
                    ]
                );
            }

            if ($analysis === GetAnalysisError::Forbidden) {
                $account = $this->api->getTokenInformation($_locale);
                if ($account instanceof Token) {
                    return $this->forward(
                        ErrorController::class . '::forbidden',
                        [
                            ...$request->attributes->all(),
                        ]
                    );
                }

                return $this->forward(
                    ErrorController::class . '::apiAccessForbidden',
                    [
                        '_locale' => $_locale,
                        ...$request->attributes->all(),
                    ]
                );
            }

            if ($analysis === GetAnalysisError::NoSuchAnalysis) {
                // Edge case when the API forgets the analysis exists.
                $this->analyses->remove($analysisFactory->cached(), true);
                return $this->redirectToRoute('app_page_analysis_register');
            }

            if ($analysis === GetAnalysisError::UnknownError &&
                !$this->api->checkInternetConnectivity($_locale)
            ) {
                return $this->forward(
                    ErrorController::class . '::offline',
                    [
                        '_locale' => $_locale,
                        ...$request->attributes->all(),
                    ]
                );
            }

            throw new RuntimeError('Fetching analysis failed.');
        }

        if ($analysis->getStatus()->isFinished()) {
            $this->addFlash(
                $analysis->getStatus() === AnalysisStatus::completed ?
                    'success' :
                    'danger',
                $analysis->getFinishedReason()
            );

            if ($analysis->getStatus() === AnalysisStatus::crashed) {
                $this->addFlash(
                    'info',
                    [
                        'message' => $i18n->trans(
                            'Don’t know why your analysis was stopped? Check our <a href=%url%>User Manual</a>.',
                            [
                                '%url%' => $portal($_locale) . '/' .
                                    $i18n->trans('typo3_slug_user_manual')
                            ]
                        ),
                        'raw' => true,
                        'icon' => 'bi bi-question-circle text-info'
                    ]
                );
            }

            self::addUploadErrors(
                $this,
                $analysisFactory,
                $analysis,
                $i18n
            );

            $this->analyses->remove($analysisFactory->cached(), true);
            return $this->redirectToRoute('app_page_analysis_register');
        }

        $actions = $this->analysisActions(
            $request,
            $analysisFactory->cached(),
            $i18n,
        );

        if ($actions instanceof Response) {
            return $actions;
        }

        self::addUploadErrors(
            $this,
            $analysisFactory,
            $analysis,
            $i18n
        );

        $params = array_map(
            fn(FormInterface $form) => $form->createView(),
            $actions
        );

        $params['currentFile'] = $this->getCurrentFile();

        return $this->render(
            'pages/analysis/show.html.twig',
            $params,
        );
    }

    private function getCurrentFile(): string
    {
        $upload = $this->uploads->findBy(
            ['analysis' => $this->analyses->current()->localUuid],
            ['id' => Criteria::DESC],
        );

        if (!$upload) {
            return '';
        }

        $parts = explode('/', $upload[0]->fileName);

        return array_pop($parts);
    }

    private function analysisActions(
        Request $request,
        Analysis $analysis,
        TranslatorInterface $i18n,
    ): Response|array {
        /** @var array<string, FormInterface> $forms */
        $forms = [
            'resume' => $this->forms->createNamed(
                AnalysisStatus::running->value,
                UpdateStatusType::class,
                options: [
                    'status' => AnalysisStatus::running,
                    'label' => 'Continue',
                    'class' => 'btn btn-primary',
                    'icon' => 'play-circle'
                ]
            ),
            'pause' => $this->forms->createNamed(
                AnalysisStatus::paused->value,
                UpdateStatusType::class,
                options: [
                    'status' => AnalysisStatus::paused,
                    'label' => 'Pause',
                    'class' => 'btn btn-primary',
                    'icon' => 'pause-circle'
                ]
            ),
            'finish' => $this->forms->createNamed(
                AnalysisStatus::completed->value,
                UpdateStatusType::class,
                options: [
                    'status' => AnalysisStatus::completed,
                    'label' => 'Finish analysis',
                    'class' => 'btn btn-primary',
                ]
            ),
            'cancel' => $this->forms->createNamed(
                AnalysisStatus::crashed->value,
                UpdateStatusType::class,
                options: [
                    'status' => AnalysisStatus::crashed,
                    'label' => 'Cancel analysis',
                    'class' => 'btn btn-danger',
                ]
            ),
        ];

        foreach ($forms as $form) {
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $newStatus = $form->getData();
                assert($newStatus instanceof UpdateStatus);

                $updated = $this->api->updateStatus(
                    $request->getLocale(),
                    $analysis,
                    $newStatus->getStatus(),
                );

                if ($updated instanceof UpdateStatusError) {
                    if ($analysis === GetAnalysisError::InvalidToken) {
                        return $this->forward(
                            ErrorController::class . '::invalidToken',
                            [
                                '_locale' => $request->getLocale(),
                                ...$request->attributes->all(),
                            ]
                        );
                    }

                    if ($analysis === GetAnalysisError::Forbidden) {
                        return $this->forward(
                            ErrorController::class . '::apiAccessForbidden',
                            [
                                '_locale' => $request->getLocale(),
                                ...$request->attributes->all(),
                            ]
                        );
                    }

                    if ($analysis === GetAnalysisError::UnknownError &&
                        !$this->api->checkInternetConnectivity(
                            $request->getLocale()
                        )
                    ) {
                        return $this->forward(
                            ErrorController::class . '::offline',
                            [
                                '_locale' => $request->getLocale(),
                                ...$request->attributes->all(),
                            ]
                        );
                    }

                    $this->addFlash(
                        'danger',
                        $i18n->trans(
                            UpdateStatusError::UnknownError->name

src/docker/buildfiles/opt/ada/app/templates/partials/analysis/show/buttons.html.twig
<div class="d-flex justify-content-start">
    {% if analysis.status.value != 'completed' and  analysis.status.value != 'crashed' %}
        <button type="button"
                class="btn text-danger me-2"
                data-bs-toggle="modal"
                data-bs-target="#modal-cancelAnalysis">
            <i class="bi bi-trash3"></i>
            {{ 'Cancel' | trans }}
        </button>
        {% include 'partials/modal.html.twig' with {
            'modalTitle': 'Cancel analysis' | trans,
            'modalBody': 'Are you sure you want to cancel the current analysis?' | trans,
            'modalButton': cancel,
            'modalBorderType': 'danger',
            'modalId': 'cancelAnalysis',
            'modalShowCancelButton': true,
            'modalWidth': '300'
        } %}
    {% endif %}

    {% if analysis.status.value == 'paused' %}
        {{ form(resume, {'attr': {'class': 'border-0 p-0'}}) }}
    {% endif %}

    {% if analysis.status.value == 'running' %}
        {{ form(pause, {'attr': {'class': 'border-0 p-0'}}) }}
    {% endif %}

    {% if analysis.status.value == 'running' or analysis.status.value == 'paused' %}
        <button type="button"
                class="btn btn-dark ms-3"
                data-bs-toggle="modal"
                data-bs-target="#modal-finishAnalysis">
            <i class="bi bi-check-circle"></i>
            {{ 'Finish' | trans }}
        </button>
        {% include 'partials/modal.html.twig' with {
            'modalTitle': 'Finish analysis' | trans,
            'modalBody': 'Are you sure you want to finish the current analysis?' | trans,
            'modalButton': finish,
            'modalBorderType': 'dark',
            'modalId': 'finishAnalysis',
            'modalShowCancelButton': true,
            'modalWidth': '300'
        } %}
    {% endif %}

    {% if analysis.status == 'crashed' or analysis.status == 'completed' %}
        <a href="{{ path('app_page_analysis_register') }}" class="btn btn-primary">
            <i class="bi bi-eyedropper"></i>
            {{ 'Launch an analysis' | trans }}
        </a>
    {% endif %}
</div>

src/docker/buildfiles/opt/ada/app/templates/partials/analysis/show/facts.html.twig
<div class="d-table layout-list">
    {% include 'partials/facts.html.twig' with {
        'label': 'Reference database' | trans,
        'value': analysis.type.name | trans
    } %}
    {% include 'partials/facts.html.twig' with {
        'label': 'Format of raw data' | trans,
        'value': analysis.format.value | trans
    } %}

    {% if analysis.host %}
        {% include 'partials/facts.html.twig' with {
            'label': 'Host plant' | trans,
            'value': analysis.host
        } %}
    {% endif %}

    {% include 'partials/facts.html.twig' with {
        'label': 'Country of sample origin' | trans,
        'value': analysis.countryName
    } %}

    {% if analysis.city %}
        {% include 'partials/facts.html.twig' with {
            'label': 'Location of sample collection' | trans,
            'value': analysis.city
        } %}
    {% endif %}

    {% if analysis.longitude or analysis.latitude %}
        <dl class="d-table-row">
            <dt class="d-table-cell strong">
                {{ 'Geolocation of sample collection site' | trans }}:
            </dt>
            <dd class="d-table-cell px-3">
                <div class="d-table">
                    {% if analysis.longitude %}
                        <dl class="d-table-row">
                            <dt class="d-table-cell">
                                {{ 'Longitude' | trans }}:
                            </dt>
                            <dd class="d-table-cell px-2">
                                {{ analysis.longitude }}
                            </dd>
                        </dl>
                    {% endif %}

                    {% if analysis.latitude %}
                        <dl class="d-table-row">
                            <dt class="d-table-cell">
                                {{ 'Latitude' | trans }}:
                            </dt>
                            <dd class="d-table-cell px-2">
                                {{ analysis.latitude }}
                            </dd>
                        </dl>
                    {% endif %}
                </div>
            </dd>
        </dl>
    {% endif %}
</div>

src/docker/buildfiles/opt/ada/app/templates/partials/analysis/show/state.html.twig
<div class="d-table mb-3">
    {% if analysis.status.value == 'running' %}
        {% include 'partials/states/dates.html.twig' with {
            'dateStart': analysis.created
        } %}
    {% endif %}

    {% if analysis.status.value == 'paused' %}
        {# ToDo datePaused removed, doesn't exist. Maybe show runUntil instead. #}
        {% include 'partials/states/dates.html.twig' with {
            'dateStart': analysis.created,
            'dateShutdown': analysis.runUntil
        } %}
    {% endif %}

    {% if analysis.status.value == 'completed' %}
        {% include 'partials/states/dates.html.twig' with {
            'dateStart': analysis.created,
            'dateCompleted': analysis.finishedTime
        } %}
    {% endif %}

    {% if analysis.status.value == 'crashed' %}
        {% include 'partials/states/dates.html.twig' with {
            'dateStart': analysis.created,
            'dateCrashed': analysis.finishedTime
        } %}
    {% endif %}

    {% include 'partials/facts.html.twig' with {
        'label': 'Duration' | trans,
        'value': "#{analysis.runningTime.hours}h #{analysis.runningTime.minutes}m"
    } %}

    {% include 'partials/facts.html.twig' with {
        'label': 'Upload folder' | trans,
        'value': analysisFactory.cached.relativeDataPath
    } %}
    {% include 'partials/facts.html.twig' with {
        'label': 'Number of files uploaded' | trans,
        'value': analysis.uploaded | length
    } %}

    {% include 'partials/facts.html.twig' with {
        'label': 'Current file' | trans,
        'value': currentFile
    } %}
</div>